const gameHTML = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tic-Tac-Toe</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #fff8f0;
            color: #e65100;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }
        h1 {
            margin-bottom: 20px;
            color: #e65100;
        }
        .status {
            font-size: 1.5rem;
            margin-bottom: 20px;
            color: #e65100;
        }
        .board {
            display: grid;
            grid-template-columns: repeat(3, 100px);
            grid-template-rows: repeat(3, 100px);
            gap: 10px;
            background-color: #ffffff;
            padding: 10px;
            border-radius: 10px;
            box-shadow: 0 10px 20px rgba(0,0,0,0.1);
        }
        .cell {
            background-color: #ffffff;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 3rem;
            font-weight: bold;
            cursor: pointer;
            user-select: none;
            border-radius: 5px;
            transition: background-color 0.2s;
        }
        .cell:hover {
            background-color: #fff3e0;
        }
        .cell.x {
            color: #ff5722;
        }
        .cell.o {
            color: #ffffff;
        }
        button {
            margin-top: 30px;
            padding: 12px 24px;
            font-size: 1.1rem;
            cursor: pointer;
            background-color: #ff9800;
            color: white;
            border: none;
            border-radius: 5px;
            transition: background-color 0.2s;
        }
        button:hover {
            background-color: #f57c00;
        }
    </style>
</head>
<body>
    <h1>Tic-Tac-Toe</h1>
    <div class="status" id="status">Player X's turn</div>
    <div class="board" id="board">
        <!-- Cells will be generated by JavaScript -->
    </div>
    <button id="reset">Reset Game</button>

    <script>
        const boardElement = document.getElementById('board');
        const statusElement = document.getElementById('status');
        const resetButton = document.getElementById('reset');
        
        let board = ['', '', '', '', '', '', '', '', ''];
        let currentPlayer = 'X';
        let gameActive = true;

        const winningConditions = [
            [0, 1, 2], [3, 4, 5], [6, 7, 8],
            [0, 3, 6], [1, 4, 7], [2, 5, 8],
            [0, 4, 8], [2, 4, 6]
        ];

        function createBoard() {
            boardElement.innerHTML = '';
            board.forEach((cell, index) => {
                const cellElement = document.createElement('div');
                cellElement.classList.add('cell');
                cellElement.setAttribute('data-index', index);
                cellElement.addEventListener('click', handleCellClick);
                boardElement.appendChild(cellElement);
            });
        }

        function handleCellClick(e) {
            const clickedCell = e.target;
            const clickedCellIndex = parseInt(clickedCell.getAttribute('data-index'));

            if (board[clickedCellIndex] !== '' || !gameActive) {
                return;
            }

            handleCellPlayed(clickedCell, clickedCellIndex);
            handleResultValidation();
        }

        function handleCellPlayed(clickedCell, clickedCellIndex) {
            board[clickedCellIndex] = currentPlayer;
            clickedCell.innerText = currentPlayer;
            clickedCell.classList.add(currentPlayer.toLowerCase());
        }

        function handleResultValidation() {
            let roundWon = false;
            for (let i = 0; i <= 7; i++) {
                const winCondition = winningConditions[i];
                let a = board[winCondition[0]];
                let b = board[winCondition[1]];
                let c = board[winCondition[2]];
                if (a === '' || b === '' || c === '') {
                    continue;
                }
                if (a === b && b === c) {
                    roundWon = true;
                    break;
                }
            }

            if (roundWon) {
                statusElement.innerText = `Player ${currentPlayer} wins!`;
                gameActive = false;
                return;
            }

            let roundDraw = !board.includes('');
            if (roundDraw) {
                statusElement.innerText = 'Game Draw!';
                gameActive = false;
                return;
            }

            handlePlayerChange();
        }

        function handlePlayerChange() {
            currentPlayer = currentPlayer === 'X' ? 'O' : 'X';
            statusElement.innerText = `Player ${currentPlayer}'s turn`;
        }

        function handleRestartGame() {
            gameActive = true;
            currentPlayer = 'X';
            board = ['', '', '', '', '', '', '', '', ''];
            statusElement.innerText = `Player ${currentPlayer}'s turn`;
            createBoard();
        }

        resetButton.addEventListener('click', handleRestartGame);
        createBoard();
    </script>
</body>
</html>
`;

document.body.innerHTML = gameHTML;